services:
  - type: web
    name: mobile-benchmarking-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mobile-benchmarking-system.onrender.com 